### ISSUE TITLE
summary issue with simulation

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/bbi#224]
When simulating nonmem model without estimation, bbi summary bugs out:

```
barrettk@ip-10-128-28-193:/data/RtmpsgSpGf-NONMEM-tests$ bbi nonmem summary 1001/1001.lst
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
bbi/parsers/nmparser.CheckIfNotGradientBased(0xc000020638, 0x5, 0x7fe7d7, 0xa, 0xc000016b40, 0x1c, 0xc1cdcd64ff800000, 0xc1cdcd64ff800000, 0x3fd353f7ced91687, 0xffffffffc4653601, ...)
        /drone/src/parsers/nmparser/utils.go:25 +0x12f
bbi/parsers/nmparser.GetModelOutput(0x7fffc8e60e9b, 0xd, 0xe07728f8ffffff00, 0x0, 0x0, 0xf058f8faffff0101, 0x0, 0x0, 0x0, 0x0, ...)
        /drone/src/parsers/nmparser/get_model_output.go:57 +0x499
bbi/cmd.summary(0xa756a0, 0xc00005d750, 0x1, 0x1)
        /drone/src/cmd/summary.go:61 +0xa85
github.com/spf13/cobra.(*Command).execute(0xa756a0, 0xc00005d720, 0x1, 0x1, 0xa756a0, 0xc00005d720)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xa74c20, 0x12, 0xc00017df28, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
bbi/cmd.Execute(0x0, 0x0)
        /drone/src/cmd/root.go:67 +0xee
main.main()
        /drone/src/cmd/bbi/main.go:17 +0x39
```

**Comment by barrettk** [comment]
This folder has all the data, models and output to rerun if necessary:

[bbi_simulationBug.zip](https://github.com/metrumresearchgroup/bbi/files/6962696/bbi_simulationBug.zip)
