### ISSUE TITLE
refactor all tests in bbi to use wrapt

### ISSUE THREAD

**Issue by seth127** [metrumresearchgroup/bbi#237]

**Comment by seth127** [comment]
Ideally the output of this ticket will be a clean list of current tests in the repo and the result when you run them. However, last time I tried they didn't even seem to run (see below), so if there is additional work required to get that clean list then let's split that off into a new issue.

### current test output

Run in the GoLand terminal on my local MacBook
```
$ go test ./...
# bbi/cmd
cmd/params.go:109:4: Infof format %s has arg len(potentialModelDirs) of wrong type int
cmd/params.go:110:4: Infof format %s has arg len(modelsInDir.List()) of wrong type int
FAIL	bbi/cmd [build failed]
?   	bbi/cmd/bbi	[no test files]
?   	bbi/configlib	[no test files]
--- FAIL: TestParseBlockResultsSigma (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
testing.tRunner.func1.2({0x11dac00, 0xc0000dc450})
	/usr/local/opt/go/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/opt/go/libexec/src/testing/testing.go:1212 +0x218
panic({0x11dac00, 0xc0000dc450})
	/usr/local/opt/go/libexec/src/runtime/panic.go:1038 +0x215
bbi/parsers/nmparser.TestParseBlockResultsSigma(0xc00013d860)
	/Users/SethG/go/src/github.com/metrumresearchgroup/bbi/parsers/nmparser/parse_final_parameter_estimates_test.go:124 +0x313
testing.tRunner(0xc00013d860, 0x120c068)
	/usr/local/opt/go/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/opt/go/libexec/src/testing/testing.go:1306 +0x35a
FAIL	bbi/parsers/nmparser	0.112s
ok  	bbi/runner	(cached)
?   	bbi/scratch	[no test files]
ok  	bbi/utils	(cached)
?   	bbi/xmlparser	[no test files]
FAIL
```

**Comment by elisarver** [comment]
I fixed a lot of the tests that were panicking I think, and DJ's work to fix the system that runs the test on the grid seems to have cleared the rest out for us
